# Generated by Django 4.1.7 on 2023-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('Full name', 'Full Name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain Name'), ('Phone number', 'Phone Number'), ('Company name', 'Company Name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=64)),
                ('index', models.PositiveSmallIntegerField()),
                ('min', models.PositiveSmallIntegerField(null=True)),
                ('max', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='schema',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='columns',
            field=models.ManyToManyField(to='csv_data.column'),
        ),
    ]
