from django.contrib.auth import get_user_model
from django.db import models


class UserFile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    file = models.FileField(help_text="File generated by the user")
